language: scala

sudo: required

before_install:
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' > /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get -qq update
  - sudo apt-get install --force-yes mono-devel

jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.1

before_script: cd scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal test

notifications:
  email:
    recipients:
      - marko.elezovic@oradian.com
